### ISSUE TITLE
Practica Back End

### ISSUE THREAD

**Issue by MaGuadalupeQuiroz** [SistemasTecTlaxiaco/practica-back-end-pc-box#2]
[Back end login.pdf](https://github.com/SistemasTecTlaxiaco/practica-back-end-pc-box/files/6548704/Back.end.login.pdf)

**Comment by Edwin-1012** [comment]
Contienen todos los datos requeridos y cumplen con lo especificado 30%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
